# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import lp_rpc_pb2 as lp__rpc__pb2
GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lp_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub(object):
    """RPC calls implemented by the orchestrator
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrchestrator = channel.unary_unary(
                '/net.Orchestrator/GetOrchestrator',
                request_serializer=lp__rpc__pb2.OrchestratorRequest.SerializeToString,
                response_deserializer=lp__rpc__pb2.OrchestratorInfo.FromString,
                _registered_method=True)
        self.EndTranscodingSession = channel.unary_unary(
                '/net.Orchestrator/EndTranscodingSession',
                request_serializer=lp__rpc__pb2.EndTranscodingSessionRequest.SerializeToString,
                response_deserializer=lp__rpc__pb2.EndTranscodingSessionResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/net.Orchestrator/Ping',
                request_serializer=lp__rpc__pb2.PingPong.SerializeToString,
                response_deserializer=lp__rpc__pb2.PingPong.FromString,
                _registered_method=True)


class OrchestratorServicer(object):
    """RPC calls implemented by the orchestrator
    """

    def GetOrchestrator(self, request, context):
        """Called by the broadcaster to request transcoder info from an orchestrator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndTranscodingSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrchestrator': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrchestrator,
                    request_deserializer=lp__rpc__pb2.OrchestratorRequest.FromString,
                    response_serializer=lp__rpc__pb2.OrchestratorInfo.SerializeToString,
            ),
            'EndTranscodingSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndTranscodingSession,
                    request_deserializer=lp__rpc__pb2.EndTranscodingSessionRequest.FromString,
                    response_serializer=lp__rpc__pb2.EndTranscodingSessionResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=lp__rpc__pb2.PingPong.FromString,
                    response_serializer=lp__rpc__pb2.PingPong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'net.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('net.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """RPC calls implemented by the orchestrator
    """

    @staticmethod
    def GetOrchestrator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/net.Orchestrator/GetOrchestrator',
            lp__rpc__pb2.OrchestratorRequest.SerializeToString,
            lp__rpc__pb2.OrchestratorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndTranscodingSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/net.Orchestrator/EndTranscodingSession',
            lp__rpc__pb2.EndTranscodingSessionRequest.SerializeToString,
            lp__rpc__pb2.EndTranscodingSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/net.Orchestrator/Ping',
            lp__rpc__pb2.PingPong.SerializeToString,
            lp__rpc__pb2.PingPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AIWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAIWorker = channel.unary_stream(
                '/net.AIWorker/RegisterAIWorker',
                request_serializer=lp__rpc__pb2.RegisterAIWorkerRequest.SerializeToString,
                response_deserializer=lp__rpc__pb2.NotifyAIJob.FromString,
                _registered_method=True)


class AIWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAIWorker(self, request, context):
        """Called by the aiworker to register to an orchestrator. The orchestrator
        notifies registered aiworkers of jobs as they come in.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAIWorker': grpc.unary_stream_rpc_method_handler(
                    servicer.RegisterAIWorker,
                    request_deserializer=lp__rpc__pb2.RegisterAIWorkerRequest.FromString,
                    response_serializer=lp__rpc__pb2.NotifyAIJob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'net.AIWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('net.AIWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAIWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/net.AIWorker/RegisterAIWorker',
            lp__rpc__pb2.RegisterAIWorkerRequest.SerializeToString,
            lp__rpc__pb2.NotifyAIJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TranscoderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTranscoder = channel.unary_stream(
                '/net.Transcoder/RegisterTranscoder',
                request_serializer=lp__rpc__pb2.RegisterRequest.SerializeToString,
                response_deserializer=lp__rpc__pb2.NotifySegment.FromString,
                _registered_method=True)


class TranscoderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterTranscoder(self, request, context):
        """Called by the transcoder to register to an orchestrator. The orchestrator
        notifies registered transcoders of segments as they come in.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTranscoder': grpc.unary_stream_rpc_method_handler(
                    servicer.RegisterTranscoder,
                    request_deserializer=lp__rpc__pb2.RegisterRequest.FromString,
                    response_serializer=lp__rpc__pb2.NotifySegment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'net.Transcoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('net.Transcoder', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transcoder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTranscoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/net.Transcoder/RegisterTranscoder',
            lp__rpc__pb2.RegisterRequest.SerializeToString,
            lp__rpc__pb2.NotifySegment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
